server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    enableSelfPreservation: false
spring:
  boot:
    admin:
      context-path: /admin

  application:
    name: car-dashboard-discovery

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS